### ISSUE TITLE
Running coverage with typescript support (bug?)

### ISSUE THREAD

**Issue by alsco77** [FormidableLabs/builder#184]
### What

I am currently trying to migrate from a truffle project to Buidler -> https://github.com/mstable/mStable-contracts/pull/89

As you can see from the `buidler.config.ts`, the test suite is written in Typescript.

### Issue

Running `yarn buidler coverage --network coverage --solcoverjs ./.solcover.js --testfiles test/**/Test*.ts --show-stack-traces` results in the following output:

```
Error BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.ts

Error: BDLR308: Unrecognized positional argument test/governance/TestDelayedClaimableGovernor.spec.ts
    at ArgumentsParser._parsePositionalParamArgs (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/ArgumentsParser.ts:271:13)
    at ArgumentsParser.parseTaskArguments (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/ArgumentsParser.ts:113:38)
    at main (/home/alex/projects/stability-labs/mstable/mStable-contracts/node_modules/@nomiclabs/buidler/src/internal/cli/cli.ts:128:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Outcome

Bug, lack of feature or simply incorrect usage?

**Comment by alsco77** [comment]
Wrong repo. Woops
