### ISSUE TITLE
Make `builder` -> `builder help` rather than displaying actions error

### ISSUE THREAD

**Issue by baer** [FormidableLabs/builder#61]
Perhaps the default behavior should be `builder help` as is the case with tools like git, npm and many others.

```
/Users/<user>/dev/tmp/builder-test/node_modules/builder/lib/task.js:42
    throw new Error("Invalid action: " + this._action +
    ^

Error: Invalid action: undefined - Valid actions: help, run, concurrent, envs
    at new module.exports (/Users/ebaer/dev/tmp/builder-test/node_modules/builder/lib/task.js:42:11)
    at module.exports (/Users/ebaer/dev/tmp/builder-test/node_modules/builder/bin/builder-core.js:17:14)
    at Object.<anonymous> (/Users/ebaer/dev/tmp/builder-test/node_modules/builder/bin/builder.js:24:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**Comment by exogen** [comment]
Just so it's tracked: `git` alone (for example) still returns exit code `1` and `git help` exit code 0, but the do print the same thing.
